import { MigrationInterface, QueryRunner } from "typeorm";

export class InitAllTables1766991829049 implements MigrationInterface {
    name = 'InitAllTables1766991829049'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "temporary_products" ("id" varchar PRIMARY KEY NOT NULL, "productName" varchar NOT NULL, "shortDescription" varchar NOT NULL, "description" text NOT NULL, "media" text, "price" decimal(10,2) NOT NULL, "stock" integer NOT NULL, "createdBy" varchar NOT NULL, "postDay" datetime NOT NULL DEFAULT (datetime('now')), "editReason" varchar, "deleted" boolean NOT NULL DEFAULT (0), "likes" integer NOT NULL DEFAULT (0), "likedUsers" text DEFAULT ('{}'), "keywords" text array)`);
        await queryRunner.query(`INSERT INTO "temporary_products"("id", "productName", "shortDescription", "description", "media", "price", "stock", "createdBy", "postDay", "editReason", "deleted", "likes", "likedUsers", "keywords") SELECT "id", "productName", "shortDescription", "description", "media", "price", "stock", "createdBy", "postDay", "editReason", "deleted", "likes", "likedUsers", "keywords" FROM "products"`);
        await queryRunner.query(`DROP TABLE "products"`);
        await queryRunner.query(`ALTER TABLE "temporary_products" RENAME TO "products"`);
        await queryRunner.query(`CREATE TABLE "temporary_order" ("id" varchar PRIMARY KEY NOT NULL, "userId" varchar NOT NULL, "products" json NOT NULL, "totalAmount" float NOT NULL, "status" varchar CHECK( "status" IN ('pending','paid','shipped','delivered','cancelled','returned','partial_cancelled','partial_returned') ) NOT NULL DEFAULT ('pending'), "cancelReason" varchar, "returnReason" varchar, "createdAt" datetime NOT NULL, "updatedAt" datetime, "price" real NOT NULL DEFAULT (0), CONSTRAINT "FK_caabe91507b3379c7ba73637b84" FOREIGN KEY ("userId") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_order"("id", "userId", "products", "totalAmount", "status", "cancelReason", "returnReason", "createdAt", "updatedAt", "price") SELECT "id", "userId", "products", "totalAmount", "status", "cancelReason", "returnReason", "createdAt", "updatedAt", "price" FROM "order"`);
        await queryRunner.query(`DROP TABLE "order"`);
        await queryRunner.query(`ALTER TABLE "temporary_order" RENAME TO "order"`);
        await queryRunner.query(`CREATE TABLE "temporary_products" ("id" varchar PRIMARY KEY NOT NULL, "productName" varchar NOT NULL, "shortDescription" varchar NOT NULL, "description" text NOT NULL, "media" text, "price" decimal(10,2) NOT NULL, "stock" integer NOT NULL, "createdBy" varchar NOT NULL, "postDay" datetime NOT NULL DEFAULT (datetime('now')), "editReason" varchar, "deleted" boolean NOT NULL DEFAULT (0), "likes" integer NOT NULL DEFAULT (0), "likedUsers" text DEFAULT ('{}'), "keywords" text array)`);
        await queryRunner.query(`INSERT INTO "temporary_products"("id", "productName", "shortDescription", "description", "media", "price", "stock", "createdBy", "postDay", "editReason", "deleted", "likes", "likedUsers", "keywords") SELECT "id", "productName", "shortDescription", "description", "media", "price", "stock", "createdBy", "postDay", "editReason", "deleted", "likes", "likedUsers", "keywords" FROM "products"`);
        await queryRunner.query(`DROP TABLE "products"`);
        await queryRunner.query(`ALTER TABLE "temporary_products" RENAME TO "products"`);
        await queryRunner.query(`CREATE TABLE "temporary_order" ("id" varchar PRIMARY KEY NOT NULL, "userId" varchar NOT NULL, "products" json NOT NULL, "totalAmount" float NOT NULL, "status" varchar CHECK( "status" IN ('pending','paid','shipped','delivered','cancelled','returned','partial_cancelled','partial_returned') ) NOT NULL DEFAULT ('pending'), "cancelReason" varchar, "returnReason" varchar, "createdAt" datetime NOT NULL, "updatedAt" datetime, "price" real, CONSTRAINT "FK_caabe91507b3379c7ba73637b84" FOREIGN KEY ("userId") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_order"("id", "userId", "products", "totalAmount", "status", "cancelReason", "returnReason", "createdAt", "updatedAt", "price") SELECT "id", "userId", "products", "totalAmount", "status", "cancelReason", "returnReason", "createdAt", "updatedAt", "price" FROM "order"`);
        await queryRunner.query(`DROP TABLE "order"`);
        await queryRunner.query(`ALTER TABLE "temporary_order" RENAME TO "order"`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "order" RENAME TO "temporary_order"`);
        await queryRunner.query(`CREATE TABLE "order" ("id" varchar PRIMARY KEY NOT NULL, "userId" varchar NOT NULL, "products" json NOT NULL, "totalAmount" float NOT NULL, "status" varchar CHECK( "status" IN ('pending','paid','shipped','delivered','cancelled','returned','partial_cancelled','partial_returned') ) NOT NULL DEFAULT ('pending'), "cancelReason" varchar, "returnReason" varchar, "createdAt" datetime NOT NULL, "updatedAt" datetime, "price" real NOT NULL DEFAULT (0), CONSTRAINT "FK_caabe91507b3379c7ba73637b84" FOREIGN KEY ("userId") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "order"("id", "userId", "products", "totalAmount", "status", "cancelReason", "returnReason", "createdAt", "updatedAt", "price") SELECT "id", "userId", "products", "totalAmount", "status", "cancelReason", "returnReason", "createdAt", "updatedAt", "price" FROM "temporary_order"`);
        await queryRunner.query(`DROP TABLE "temporary_order"`);
        await queryRunner.query(`ALTER TABLE "products" RENAME TO "temporary_products"`);
        await queryRunner.query(`CREATE TABLE "products" ("id" varchar PRIMARY KEY NOT NULL, "productName" varchar NOT NULL, "shortDescription" varchar NOT NULL, "description" text NOT NULL, "media" text, "price" decimal(10,2) NOT NULL, "stock" integer NOT NULL, "createdBy" varchar NOT NULL, "postDay" datetime NOT NULL DEFAULT (datetime('now')), "editReason" varchar, "deleted" boolean NOT NULL DEFAULT (0), "likes" integer NOT NULL DEFAULT (0), "likedUsers" text DEFAULT ('{}'), "keywords" text array)`);
        await queryRunner.query(`INSERT INTO "products"("id", "productName", "shortDescription", "description", "media", "price", "stock", "createdBy", "postDay", "editReason", "deleted", "likes", "likedUsers", "keywords") SELECT "id", "productName", "shortDescription", "description", "media", "price", "stock", "createdBy", "postDay", "editReason", "deleted", "likes", "likedUsers", "keywords" FROM "temporary_products"`);
        await queryRunner.query(`DROP TABLE "temporary_products"`);
        await queryRunner.query(`ALTER TABLE "order" RENAME TO "temporary_order"`);
        await queryRunner.query(`CREATE TABLE "order" ("id" varchar PRIMARY KEY NOT NULL, "userId" varchar NOT NULL, "products" json NOT NULL, "totalAmount" float NOT NULL, "status" varchar CHECK( "status" IN ('pending','paid','shipped','delivered','cancelled','returned','partial_cancelled','partial_returned') ) NOT NULL DEFAULT ('pending'), "cancelReason" varchar, "returnReason" varchar, "createdAt" datetime NOT NULL, "updatedAt" datetime, "price" real NOT NULL DEFAULT (0), CONSTRAINT "FK_caabe91507b3379c7ba73637b84" FOREIGN KEY ("userId") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "order"("id", "userId", "products", "totalAmount", "status", "cancelReason", "returnReason", "createdAt", "updatedAt", "price") SELECT "id", "userId", "products", "totalAmount", "status", "cancelReason", "returnReason", "createdAt", "updatedAt", "price" FROM "temporary_order"`);
        await queryRunner.query(`DROP TABLE "temporary_order"`);
        await queryRunner.query(`ALTER TABLE "products" RENAME TO "temporary_products"`);
        await queryRunner.query(`CREATE TABLE "products" ("id" varchar PRIMARY KEY NOT NULL, "productName" varchar NOT NULL, "shortDescription" varchar NOT NULL, "description" text NOT NULL, "media" text, "price" decimal(10,2) NOT NULL, "stock" integer NOT NULL, "createdBy" varchar NOT NULL, "postDay" datetime NOT NULL DEFAULT (datetime('now')), "editReason" varchar, "deleted" boolean NOT NULL DEFAULT (0), "likes" integer NOT NULL DEFAULT (0), "likedUsers" text DEFAULT ('{}'), "keywords" text array)`);
        await queryRunner.query(`INSERT INTO "products"("id", "productName", "shortDescription", "description", "media", "price", "stock", "createdBy", "postDay", "editReason", "deleted", "likes", "likedUsers", "keywords") SELECT "id", "productName", "shortDescription", "description", "media", "price", "stock", "createdBy", "postDay", "editReason", "deleted", "likes", "likedUsers", "keywords" FROM "temporary_products"`);
        await queryRunner.query(`DROP TABLE "temporary_products"`);
    }

}
